version: "3" #docker compose up för att köra
services:
  directus:
    image: directus/directus:10.10.5
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      CORS_ENABLED: "true"
      CORS_ORIGIN: "http://localhost:3000"
      CORS_METHODS: "GET,POST,PATCH,DELETE"
      KEY: "replace-with-random-value"
      SECRET: "replace-with-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"      
    user: root #kommentera bort detta om det ej fungerar
